version: "3.8"
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailcatcher:
    image: tophfr/mailcatcher:latest
    restart: unless-stopped
    ports:
        - "25:25"
        # Had to bind to different port as 80 was taken
        - "70:80"

